/* ============================================================
   قائمة الاحتياجات الجاهزة — مخزون بيت كامل
   تُستورد مرة واحدة عند أول فتح، ثم تصير ملكك: تضيف وتحذف كما تشاء.
   out: true تعني «ناقص الآن»؛ وما عداه متوفر.
   ============================================================ */

export const PANTRY_CATEGORIES = [
  { id: 'canned',   name: 'معلبات',               icon: '🥫' },
  { id: 'grains',   name: 'حبوب ومكرونة',         icon: '🍝' },
  { id: 'oils',     name: 'زيوت وصوصات',          icon: '🫒' },
  { id: 'spices',   name: 'بهارات',               icon: '🧂' },
  { id: 'frozen',   name: 'مأكولات مجمدة',        icon: '🧊' },
  { id: 'chilled',  name: 'مبردات',               icon: '🧀' },
  { id: 'pickles',  name: 'مخللات ومربى',         icon: '🫙' },
  { id: 'baby',     name: 'احتياجات الأطفال',     icon: '🍼' },
  { id: 'cleaning', name: 'منظفات البيت والمطبخ', icon: '🧼' },
  { id: 'kitchen',  name: 'احتياجات المطبخ',      icon: '🍽️' },
  { id: 'personal', name: 'أدوات صحية',           icon: '🧴' },
  { id: 'produce',  name: 'خضروات وفواكه',        icon: '🥬' },
];

export const PANTRY_SEED = [
  /* معلبات */
  { c: 'canned', n: 'تونة' },
  { c: 'canned', n: 'حليب قواطي' },
  { c: 'canned', n: 'كرم كراميل' },
  { c: 'canned', n: 'خميرة فورية' },
  { c: 'canned', n: 'فول' },
  { c: 'canned', n: 'حليب مكثف' },
  { c: 'canned', n: 'فاصوليا' },
  { c: 'canned', n: 'ورق عنب' },
  { c: 'canned', n: 'جلي' },
  { c: 'canned', n: 'قشطة' },
  { c: 'canned', n: 'بقسماط' },
  { c: 'canned', n: 'بيكنج بودر' },
  { c: 'canned', n: 'طحينية' },
  { c: 'canned', n: 'تانج' },
  { c: 'canned', n: 'بودرة كاكاو' },
  { c: 'canned', n: 'فطر مشروم' },
  { c: 'canned', n: 'كستر بودرة' },

  /* حبوب ومكرونة */
  { c: 'grains', n: 'طحين رقم 1' },
  { c: 'grains', n: 'ماجي' },
  { c: 'grains', n: 'إندومي' },
  { c: 'grains', n: 'كرتون كيك' },
  { c: 'grains', n: 'عيش' },
  { c: 'grains', n: 'شاي' },
  { c: 'grains', n: 'حليب نيدو متوسط' },
  { c: 'grains', n: 'معجون طماطم' },
  { c: 'grains', n: 'طحين رقم 3' },
  { c: 'grains', n: 'طحين خبز رقم 2' },
  { c: 'grains', n: 'خبز تورتيلا' },
  { c: 'grains', n: 'مكرونة سباغيتي 🍝' },
  { c: 'grains', n: 'مكرونة عادية' },
  { c: 'grains', n: 'سيواء' },
  { c: 'grains', n: 'مكرونة باستا' },
  { c: 'grains', n: 'عدس' },
  { c: 'grains', n: 'حمص حب' },
  { c: 'grains', n: 'شوفان' },
  { c: 'grains', n: 'دريم ويب' },
  { c: 'grains', n: 'عيش مصري' },
  { c: 'grains', n: 'شوربة ماجي — ظروف شعيرية وفطر' },
  { c: 'grains', n: 'شعيرية' },
  { c: 'grains', n: 'نشاء' },
  { c: 'grains', n: 'سميد' },

  /* زيوت وصوصات */
  { c: 'oils', n: 'سمن' },
  { c: 'oils', n: 'كاكاو سائل' },
  { c: 'oils', n: 'صوص برجر' },
  { c: 'oils', n: 'كاتشب' },
  { c: 'oils', n: 'مايونيز' },
  { c: 'oils', n: 'زيت طبخ' },
  { c: 'oils', n: 'صوص بيتزا' },
  { c: 'oils', n: 'عسل أو دبس' },
  { c: 'oils', n: 'دغوس' },
  { c: 'oils', n: 'ماء ورد' },
  { c: 'oils', n: 'ليمون دبة' },
  { c: 'oils', n: 'زيت زيتون' },
  { c: 'oils', n: 'صوبار' },
  { c: 'oils', n: 'دبس رمان' },
  { c: 'oils', n: 'جميد' },
  { c: 'oils', n: 'خل أبيض' },
  { c: 'oils', n: 'زيت بخاخ' },
  { c: 'oils', n: 'كراميل' },
  { c: 'oils', n: 'عصير موهيتو' },

  /* بهارات */
  { c: 'spices', n: 'جوز الهند (نارجيل)', out: true },
  { c: 'spices', n: 'سكر' },
  { c: 'spices', n: 'بسكوت' },
  { c: 'spices', n: 'زبيب' },
  { c: 'spices', n: 'فلفل أحمر' },
  { c: 'spices', n: 'كركم' },
  { c: 'spices', n: 'بهارات مكبوس مطحونة' },
  { c: 'spices', n: 'بابريكا' },
  { c: 'spices', n: 'بهارات صحيحة' },
  { c: 'spices', n: 'بودرة الزعفران' },
  { c: 'spices', n: 'كاري' },
  { c: 'spices', n: 'فلفل أسود مطحون' },
  { c: 'spices', n: 'نثيبة' },
  { c: 'spices', n: 'صنوبر أو مكسرات مشكلة' },
  { c: 'spices', n: 'نجمة ينسون' },
  { c: 'spices', n: 'قرنفل' },
  { c: 'spices', n: 'قرفة حطب' },
  { c: 'spices', n: 'ورق غار' },
  { c: 'spices', n: 'فلفل كور' },
  { c: 'spices', n: 'بهارات عمانية' },
  { c: 'spices', n: 'قرفة أعواد' },
  { c: 'spices', n: 'سنوت كمون' },
  { c: 'spices', n: 'فستق مطحون' },
  { c: 'spices', n: 'فانيلا' },
  { c: 'spices', n: 'هيل مطحون' },
  { c: 'spices', n: 'زعتر بيتزا' },
  { c: 'spices', n: 'فلفل أسود حب' },
  { c: 'spices', n: 'سماق' },
  { c: 'spices', n: 'ملح' },
  { c: 'spices', n: 'بودرة ثوم' },
  { c: 'spices', n: 'فستق' },
  { c: 'spices', n: 'زعتر' },

  /* مأكولات مجمدة */
  { c: 'frozen', n: 'دجاج ورك' },
  { c: 'frozen', n: 'بطاطس مقلية مجمدة' },
  { c: 'frozen', n: 'برجر' },
  { c: 'frozen', n: 'فيليه زنجر' },
  { c: 'frozen', n: 'روبيان' },
  { c: 'frozen', n: 'نقانق' },
  { c: 'frozen', n: 'ناجت' },
  { c: 'frozen', n: 'دجاج كاجن' },
  { c: 'frozen', n: 'دجاج 🐓' },
  { c: 'frozen', n: 'كبدة دجاج' },
  { c: 'frozen', n: 'صدور دجاج' },
  { c: 'frozen', n: 'آيس كريم' },
  { c: 'frozen', n: 'لحم 🍖' },
  { c: 'frozen', n: 'سمك 🐟' },

  /* مبردات */
  { c: 'chilled', n: 'بيض', out: true },
  { c: 'chilled', n: 'مورتديلا لحم', out: true },
  { c: 'chilled', n: 'جبن أقراص' },
  { c: 'chilled', n: 'جبن شيدر' },
  { c: 'chilled', n: 'جبن موزريلا' },
  { c: 'chilled', n: 'جبن شيدر شرائح' },
  { c: 'chilled', n: 'كريمة الطبخ' },
  { c: 'chilled', n: 'جبنة فيتا' },
  { c: 'chilled', n: 'لبنة' },
  { c: 'chilled', n: 'روب' },
  { c: 'chilled', n: 'حليب طازج' },
  { c: 'chilled', n: 'جبن حلوم' },
  { c: 'chilled', n: 'زبدة' },
  { c: 'chilled', n: 'جبن مثلثات' },
  { c: 'chilled', n: 'عجينة سمبوسة' },
  { c: 'chilled', n: 'عجينة بف باستري' },

  /* مخللات ومربى */
  { c: 'pickles', n: 'مخلل خيار' },
  { c: 'pickles', n: 'مخلل' },
  { c: 'pickles', n: 'زيتون مشوي' },
  { c: 'pickles', n: 'زيتون مقطع' },
  { c: 'pickles', n: 'زيتون' },
  { c: 'pickles', n: 'مربى' },

  /* احتياجات الأطفال */
  { c: 'baby', n: 'حليب أطفال' },
  { c: 'baby', n: 'حفاظات' },

  /* منظفات البيت والمطبخ */
  { c: 'cleaning', n: 'صابون ملابس' },
  { c: 'cleaning', n: 'معطر حمامات' },
  { c: 'cleaning', n: 'داوني' },
  { c: 'cleaning', n: 'فحم' },
  { c: 'cleaning', n: 'إسفنجة ستيل' },
  { c: 'cleaning', n: 'فانش' },
  { c: 'cleaning', n: 'كيس زبالة' },
  { c: 'cleaning', n: 'فليت' },
  { c: 'cleaning', n: 'ديتول تنظيف الأسطح' },
  { c: 'cleaning', n: 'صابون أيادي' },
  { c: 'cleaning', n: 'جيف تنظيف' },
  { c: 'cleaning', n: 'شامبو عبايات' },
  { c: 'cleaning', n: 'أكياس زبالة صغيرة' },
  { c: 'cleaning', n: 'سبراي منظف مطابخ' },
  { c: 'cleaning', n: 'صابون أواني' },
  { c: 'cleaning', n: 'كلوركس' },
  { c: 'cleaning', n: 'فانيش منظف سجاد' },
  { c: 'cleaning', n: 'معطر فرش' },
  { c: 'cleaning', n: 'منظف مراحيض' },
  { c: 'cleaning', n: 'ممسحة أراضي' },
  { c: 'cleaning', n: 'منظف زجاج' },
  { c: 'cleaning', n: 'ديتول سبراي' },
  { c: 'cleaning', n: 'مكنسة بروش' },
  { c: 'cleaning', n: 'بروش لغسيل الحمام' },
  { c: 'cleaning', n: 'بروش حمام' },

  /* احتياجات المطبخ */
  { c: 'kitchen', n: 'تغليف شفاف', out: true },
  { c: 'kitchen', n: 'مناديل مبللة للتنظيف', out: true },
  { c: 'kitchen', n: 'كلينكس عادي' },
  { c: 'kitchen', n: 'قفازات مطبخ' },
  { c: 'kitchen', n: 'كلينكس مطبخ' },
  { c: 'kitchen', n: 'فوط زجاج' },
  { c: 'kitchen', n: 'ألمنيوم' },
  { c: 'kitchen', n: 'محش خبز' },
  { c: 'kitchen', n: 'مشخل شاهي' },
  { c: 'kitchen', n: 'إسفنج غسيل' },
  { c: 'kitchen', n: 'سماط سفرة' },
  { c: 'kitchen', n: 'صحون بارسل' },
  { c: 'kitchen', n: 'كاس زجاج' },
  { c: 'kitchen', n: 'فوط مطبخ' },
  { c: 'kitchen', n: 'ورق زبدة' },
  { c: 'kitchen', n: 'أكواب زجاج' },
  { c: 'kitchen', n: 'لوح تقطيع' },
  { c: 'kitchen', n: 'إسفنج حديد' },

  /* أدوات صحية */
  { c: 'personal', n: 'منظف أذان' },
  { c: 'personal', n: 'صابون جسم' },
  { c: 'personal', n: 'لوشن أطفال' },
  { c: 'personal', n: 'شامبو أطفال' },
  { c: 'personal', n: 'شامبو' },
  { c: 'personal', n: 'لوشن' },
  { c: 'personal', n: 'فازلين' },
  { c: 'personal', n: 'مزيل عرق نيفيا' },
  { c: 'personal', n: 'معجون' },
  { c: 'personal', n: 'فوط استحمام' },
  { c: 'personal', n: 'قطن وجه' },
  { c: 'personal', n: 'نعال زنوبة' },
  { c: 'personal', n: 'فرشاة أسنان' },
  { c: 'personal', n: 'فرشاة جزاء' },
  { c: 'personal', n: 'ليفة استحمام' },
  { c: 'personal', n: 'أمواس حلاقة' },
  { c: 'personal', n: 'سجادة للحمام' },
  { c: 'personal', n: 'غسول وجه' },
  { c: 'personal', n: 'مناديل مبللة' },

  /* خضروات وفواكه */
  { c: 'produce', n: 'خس 🥬' },
  { c: 'produce', n: 'مانجو 🥭' },
  { c: 'produce', n: 'تفاح 🍏' },
  { c: 'produce', n: 'بطيخ 🍉' },
  { c: 'produce', n: 'طماطم 🍅' },
  { c: 'produce', n: 'خيار 🥒' },
  { c: 'produce', n: 'موز 🍌' },
  { c: 'produce', n: 'ليمون 🍋' },
  { c: 'produce', n: 'برتقال 🍊' },
  { c: 'produce', n: 'جزر 🥕' },
  { c: 'produce', n: 'فليفلة' },
  { c: 'produce', n: 'ليمون يابس' },
  { c: 'produce', n: 'جوافة' },
  { c: 'produce', n: 'بقدونس' },
  { c: 'produce', n: 'بطاطس 🥔' },
  { c: 'produce', n: 'رمان' },
  { c: 'produce', n: 'بصل 🧅' },
  { c: 'produce', n: 'ثوم 🧄' },
  { c: 'produce', n: 'نعناع' },
  { c: 'produce', n: 'كزبرة' },
  { c: 'produce', n: 'خوخ 🍑' },
  { c: 'produce', n: 'شمام 🍈' },
  { c: 'produce', n: 'خضروات مشكلة 🥗' },
  { c: 'produce', n: 'بصل أخضر 🥦' },
];
